services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - app-net

  streamlit:
    build: .
    container_name: streamlit
    depends_on:
      - qdrant
    ports:
      - "8501:8501"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    networks:
      - app-net
    volumes:
      - .:/app
      - /app/.venv
networks:
  app-net:

volumes:
  qdrant_data:
